openapi: '3.0.2'
info:
  title: Category RESTful API 
  description: API Spec for category RESTful
  version: '1.0'
servers:
  - url: http://localhost:4000/api/v1
paths:
  /categories:
    get:
      security:
        - ApiKeyAuth: []
      tags:
        - "Category API"
      description: List all categories
      summary: List all categories
      responses:
        '200':
          description: Success get all categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items: 
                      $ref:
                        '#/components/schemas/Category'
    post:
      security:
        - ApiKeyAuth: []
      tags:
        - "Category API"
      description: Create new category
      summary: Create new category
      requestBody:
        content:
          application/json:
            schema:
              $ref:
                '#/components/schemas/CreateOrUpdateCategory'
      responses:
        '201':
          description: Success create category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items: 
                      $ref:
                        '#/components/schemas/Category'
  /categories/{id}:
    get:
      security:
        - ApiKeyAuth: []
      tags:
        - "Category API"
      description: Get category by ID
      summary: Get category by ID
      parameters:
        - in: path
          name: id
          schema:
            type: number
            minimum: 1
          required: true
          description: The category ID

      responses:
        '200':
          description: Success get category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items: 
                      $ref:
                        '#/components/schemas/Category'
    put:
      security:
        - ApiKeyAuth: []
      tags:
        - "Category API"
      description: Update category by ID
      summary: Update category by ID
      parameters:
        - in: path
          name: id
          schema:
            type: number
            minimum: 1
          required: true
          description: The category ID
      requestBody:
        content:
          application/json:
            schema:
              $ref:
                '#components/schemas/CreateOrUpdateCategory'
      responses:
       '200':
          description: Success update category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items: 
                      $ref:
                        '#/components/schemas/Category' 
    delete:
      security:
        - ApiKeyAuth: []
      tags:
        - "Category API"
      description: Delete category by ID
      summary: Delete category by ID
      parameters:
        - in: path
          name: id
          schema:
            type: number
            minimum: 1
          required: true
          description: The category ID

      responses:
        '200':
          description: Success delete category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    CreateOrUpdateCategory:
      type: object
      properties:
        name:
          type: string 
    Category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string

